# .travis.yml
# Configuration file for Travis-CI.org hosted testing

language: ruby

rvm:
  - 1.9.2
  - 1.9.3

branches:
  only:
    - master
    - release
    - foodcritic

gemfile:
   - Gemfile

script: bundle exec rake foodcritic
